### ISSUE TITLE
Sudden halt (MPI error?) of simulation before completion

### ISSUE THREAD

**Issue by mattzett** [gemini3d/GEMINI#12]
Seems to happen when running tohoku20113D_medres example; I've not noticed this before.  Basically the simulation terminates prematurely usually one of the workers has gotten and signal 9.  Sometimes concurrent with output.

**Comment by mattzett** [comment]
using -nooutput does not alleviate the error so I don't know that it is necessarily related to binary output errors we have been chasing for a while

**Comment by mattzett** [comment]
Manifests with a 384x144x144 grid, but does not happen with 256x96x96.  Very strange; I'll try 384x128x128 - we need a small case for which we can reproduce this error...

**Comment by mattzett** [comment]
I'm also trying this commit, which was the last time I remember (successfully) running a case similar to the the example that now fails:  eb7e4fd

**Comment by mattzett** [comment]
The issue seems to be related to the removal of this line:

```if ( .NOT.present(IPIV) ) deallocate(LPIV)```

**Comment by scivision** [comment]
Fortran doesn't auto-deallocate pointer arrays if they're still in use. This might be a corner case where the compiler should auto-deallocate with the optional argument not being present, but doesn't. There isn't any harm is manually deallocating.
