### ISSUE TITLE
Better Readme instructions for manually specifying mpi image patterns

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemini#18]
Need to make it clear that the user can specify an mpi grid split manually.  Many scenarios will actually require this as the code that tries to automatically determine the split is unsophisticated and when often fail to find a satisfactory split even when one is possible.

**Comment by scivision** [comment]
Do you mean the manual grid option

**Comment by mattzett** [comment]
Correct, I've clarified the issue.  I'm happy to work on this but I need to read through the code again and remind myself of how this works.

**Comment by mattzett** [comment]
I added something to the top-level readme which I think is enough for now.
