### ISSUE TITLE
div3D producing NaNs in some 2D simulations

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemini#23]
appears with glow_beam NS example

**Comment by mattzett** [comment]
It appears to be trying to compute a derivative with a zero value for dx2...  Strange that this never was a problem before?!!

**Comment by mattzett** [comment]
This issue is that the derivative functions are trying to compute the subgrid size from the input data size rather than from the grid structure itself...  This is dangerous because various types of calculations require derivatives with a single row of ghost cells, etc...

**Comment by mattzett** [comment]
This is really quite subtle - the pointers in the derivative functions need to be computed based on the size of the input data so that the correct differentials are available to each function.  However, when checked whether we need to differentiate in a particular direction, we need to check the grid size itself in that direction (only differentiate if non-singleton).

**Comment by scivision** [comment]
so it seems likee5942452b2f1  src/numerical/calculus/div.f90 fixed this issue by using the meshgrid x% values as noted above, thanks
