### ISSUE TITLE
Root J3 current different from workers, even for homogeneous forcing

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemini#26]
1) Can be reproduced with KHI_periodic_lowres (nml or ini) with a 1x8 domain split.
2) Exists in both master and EIA.  Need to trace back from there...

**Comment by mattzett** [comment]
3) Both root and workers are including polarization currents
4) Without polarization current (capacitance) the problem goes away; the conduction current appears to be what root was giving in the case with capacitance...

**Comment by mattzett** [comment]
5) All workers and root are doing capacitance augmentation as they should.

**Comment by mattzett** [comment]
10) grad2E is the issue; zero for root, nonzero for workers...  Since the represents dE3/dx2 it should probably be close to zero???

**Comment by mattzett** [comment]
The problem was that grad2E was not being properly assigned during computation of polarization current.

**Comment by scivision** [comment]
I believe this was fixed by cc123c2
